### ISSUE TITLE
About the asymmetric motion field in the paper

### ISSUE THREAD

**Issue by JasonSheng-atp** [JunHeum/ABME#11]
![企业微信截图_16417930957228](https://user-images.githubusercontent.com/78075051/148722693-b902ff1a-25a3-425a-8eaf-5a321409f9f3.png)
Hi, I am confused about the asymmetric motion field figure above, which you put in the paper. Since we only have t=0 and t=1, it is hard to judge whether the motion is symmetric or not. In my opinion, if the right foot in the above image is lower a little bit, then the motion will be symmetric and we don't have to take asymmetric motion field into account.

**Comment by JasonSheng-atp** [comment]
I wonder if there is an occasion that we **must** take the asmmetric motion field into account?

**Comment by JunHeum** [comment]
Hi, @JasonSheng-atp.

1. Note that the above-attached figure is a toy example illustrating the difference between symmetric and asymmetric motion. As you mentioned, we only have t=0 and t=1. In practice, we estimate symmetric bilateral motions at such cases as a right foot.

2. The linear motion constraint (or symmetric fields) fails mostly when a pixel in I_t is occluded and has no matching pixel in either I_0 or I_1. Such occluded pixels belong to backgrounds in many cases. The proposed algorithm handles those pixels using asymmetric motion fields and thus improves the frame qualities in the backgrounds. The following figure demonstrates the advantage of the asymmetric motion field. The result of asymmetric motion better reconstructs the occluded facade of the building than the one of the symmetric motion.
![image](https://user-images.githubusercontent.com/45414545/148728232-02ada67b-8ea2-461f-8ddd-823f52fac10b.png)

**Comment by JasonSheng-atp** [comment]
Thank you for your quick respond. I understand your point.
