### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by hiredd** [JunHeum/ABME#7]
bicorr6 = self.bilateral_corr6(c16, c26, torch.zeros(c16.size(0), 2, c16.size(2), c16.size(3)).to(c16))
to
bicorr6 = self.bilateral_corr6(c16, c26, torch.zeros(c16.size(0), 2, c16.size(2), c16.size(3)).to(c16.device))  ?

**Comment by JunHeum** [comment]
Hi, hiredd.

.to(c16) equals to .to(c16.device).

I think you can use one of them freely.
